# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 533)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.captureButton = QtWidgets.QPushButton(self.centralWidget)
        self.captureButton.setGeometry(QtCore.QRect(30, 360, 93, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.captureButton.sizePolicy().hasHeightForWidth())
        self.captureButton.setSizePolicy(sizePolicy)
        self.captureButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.captureButton.setObjectName("captureButton")
        self.playButton = QtWidgets.QPushButton(self.centralWidget)
        self.playButton.setGeometry(QtCore.QRect(30, 400, 93, 28))
        self.playButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.playButton.setObjectName("playButton")
        self.deleteButton = QtWidgets.QPushButton(self.centralWidget)
        self.deleteButton.setGeometry(QtCore.QRect(390, 360, 93, 28))
        self.deleteButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.deleteButton.setObjectName("deleteButton")
        self.exportButton = QtWidgets.QPushButton(self.centralWidget)
        self.exportButton.setGeometry(QtCore.QRect(390, 400, 93, 28))
        self.exportButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.exportButton.setObjectName("exportButton")
        self.imageView = QtWidgets.QLabel(self.centralWidget)
        self.imageView.setGeometry(QtCore.QRect(30, 20, 441, 301))
        self.imageView.setText("")
        self.imageView.setScaledContents(True)
        self.imageView.setObjectName("imageView")
        self.currentFrameLabel = QtWidgets.QLabel(self.centralWidget)
        self.currentFrameLabel.setGeometry(QtCore.QRect(150, 370, 91, 16))
        self.currentFrameLabel.setObjectName("currentFrameLabel")
        self.numFrames = QtWidgets.QLineEdit(self.centralWidget)
        self.numFrames.setGeometry(QtCore.QRect(220, 400, 31, 22))
        self.numFrames.setFocusPolicy(QtCore.Qt.NoFocus)
        self.numFrames.setObjectName("numFrames")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(200, 400, 16, 16))
        self.label_3.setObjectName("label_3")
        self.currentFrame = QtWidgets.QSpinBox(self.centralWidget)
        self.currentFrame.setGeometry(QtCore.QRect(150, 400, 42, 22))
        self.currentFrame.setFocusPolicy(QtCore.Qt.NoFocus)
        self.currentFrame.setStyleSheet("")
        self.currentFrame.setObjectName("currentFrame")
        self.speedGroup = QtWidgets.QGroupBox(self.centralWidget)
        self.speedGroup.setGeometry(QtCore.QRect(270, 350, 111, 81))
        self.speedGroup.setCheckable(False)
        self.speedGroup.setChecked(False)
        self.speedGroup.setObjectName("speedGroup")
        self.slowRadio = QtWidgets.QRadioButton(self.speedGroup)
        self.slowRadio.setGeometry(QtCore.QRect(10, 20, 95, 20))
        self.slowRadio.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slowRadio.setChecked(False)
        self.slowRadio.setObjectName("slowRadio")
        self.mediumRadio = QtWidgets.QRadioButton(self.speedGroup)
        self.mediumRadio.setGeometry(QtCore.QRect(10, 40, 95, 20))
        self.mediumRadio.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mediumRadio.setChecked(True)
        self.mediumRadio.setObjectName("mediumRadio")
        self.fullRadio = QtWidgets.QRadioButton(self.speedGroup)
        self.fullRadio.setGeometry(QtCore.QRect(10, 60, 95, 20))
        self.fullRadio.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fullRadio.setObjectName("fullRadio")
        self.slowRadio.raise_()
        self.mediumRadio.raise_()
        self.fullRadio.raise_()
        self.mediumRadio.raise_()
        self.fullRadio.raise_()
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(90, 470, 120, 80))
        self.widget.setObjectName("widget")
        self.cameraSettings = QtWidgets.QGroupBox(self.centralWidget)
        self.cameraSettings.setGeometry(QtCore.QRect(550, 30, 191, 441))
        self.cameraSettings.setObjectName("cameraSettings")
        self.brightnessSlider = QtWidgets.QSlider(self.cameraSettings)
        self.brightnessSlider.setGeometry(QtCore.QRect(10, 40, 160, 22))
        self.brightnessSlider.setMinimum(1)
        self.brightnessSlider.setMaximum(100)
        self.brightnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessSlider.setObjectName("brightnessSlider")
        self.label = QtWidgets.QLabel(self.cameraSettings)
        self.label.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.cameraSettings)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 71, 16))
        self.label_2.setObjectName("label_2")
        self.contrastSlider = QtWidgets.QSlider(self.cameraSettings)
        self.contrastSlider.setGeometry(QtCore.QRect(10, 100, 160, 22))
        self.contrastSlider.setMinimum(-100)
        self.contrastSlider.setMaximum(100)
        self.contrastSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contrastSlider.setObjectName("contrastSlider")
        self.label_4 = QtWidgets.QLabel(self.cameraSettings)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 71, 16))
        self.label_4.setObjectName("label_4")
        self.drcComboBox = QtWidgets.QComboBox(self.cameraSettings)
        self.drcComboBox.setGeometry(QtCore.QRect(20, 160, 73, 22))
        self.drcComboBox.setMaxVisibleItems(4)
        self.drcComboBox.setMinimumContentsLength(10)
        self.drcComboBox.setModelColumn(0)
        self.drcComboBox.setObjectName("drcComboBox")
        self.drcComboBox.addItem("")
        self.drcComboBox.addItem("")
        self.drcComboBox.addItem("")
        self.drcComboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(self.cameraSettings)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 101, 16))
        self.label_5.setObjectName("label_5")
        self.exposureComboBox = QtWidgets.QComboBox(self.cameraSettings)
        self.exposureComboBox.setGeometry(QtCore.QRect(20, 220, 73, 22))
        self.exposureComboBox.setMaxVisibleItems(10)
        self.exposureComboBox.setMinimumContentsLength(4)
        self.exposureComboBox.setModelColumn(0)
        self.exposureComboBox.setObjectName("exposureComboBox")
        self.exposureComboBox.addItem("")
        self.exposureComboBox.addItem("")
        self.exposureComboBox.addItem("")
        self.exposureComboBox.addItem("")
        self.exposureComboBox.addItem("")
        self.exposureComboBox.addItem("")
        self.exposureComboBox.addItem("")
        self.exposureComboBox.addItem("")
        self.exposureComboBox.addItem("")
        self.exposureComboBox.addItem("")
        self.exposureComboBox.addItem("")
        self.exposureComboBox.addItem("")
        self.exposureComboBox.addItem("")
        self.label_6 = QtWidgets.QLabel(self.cameraSettings)
        self.label_6.setGeometry(QtCore.QRect(10, 260, 141, 16))
        self.label_6.setObjectName("label_6")
        self.exposureSlider = QtWidgets.QSlider(self.cameraSettings)
        self.exposureSlider.setGeometry(QtCore.QRect(10, 290, 160, 22))
        self.exposureSlider.setMinimum(-25)
        self.exposureSlider.setMaximum(25)
        self.exposureSlider.setOrientation(QtCore.Qt.Horizontal)
        self.exposureSlider.setObjectName("exposureSlider")
        self.flipCheckBox = QtWidgets.QCheckBox(self.cameraSettings)
        self.flipCheckBox.setGeometry(QtCore.QRect(10, 310, 81, 20))
        self.flipCheckBox.setObjectName("flipCheckBox")
        self.denoiseCheckBox = QtWidgets.QCheckBox(self.cameraSettings)
        self.denoiseCheckBox.setGeometry(QtCore.QRect(10, 330, 81, 20))
        self.denoiseCheckBox.setObjectName("denoiseCheckBox")
        self.label_7 = QtWidgets.QLabel(self.cameraSettings)
        self.label_7.setGeometry(QtCore.QRect(100, 310, 51, 16))
        self.label_7.setObjectName("label_7")
        self.effectComboBox = QtWidgets.QComboBox(self.cameraSettings)
        self.effectComboBox.setGeometry(QtCore.QRect(90, 330, 73, 22))
        self.effectComboBox.setMaxVisibleItems(10)
        self.effectComboBox.setMinimumContentsLength(4)
        self.effectComboBox.setModelColumn(0)
        self.effectComboBox.setObjectName("effectComboBox")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.effectComboBox.addItem("")
        self.label_8 = QtWidgets.QLabel(self.cameraSettings)
        self.label_8.setGeometry(QtCore.QRect(20, 370, 71, 16))
        self.label_8.setObjectName("label_8")
        self.isoSlider = QtWidgets.QSlider(self.cameraSettings)
        self.isoSlider.setGeometry(QtCore.QRect(20, 390, 160, 22))
        self.isoSlider.setMinimum(0)
        self.isoSlider.setMaximum(1600)
        self.isoSlider.setOrientation(QtCore.Qt.Horizontal)
        self.isoSlider.setObjectName("isoSlider")
        self.applyButton = QtWidgets.QPushButton(self.cameraSettings)
        self.applyButton.setGeometry(QtCore.QRect(102, 410, 71, 28))
        self.applyButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.applyButton.setObjectName("applyButton")
        self.resetButton = QtWidgets.QPushButton(self.cameraSettings)
        self.resetButton.setGeometry(QtCore.QRect(0, 410, 71, 28))
        self.resetButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.resetButton.setObjectName("resetButton")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 786, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuStop_Motion_Studio = QtWidgets.QMenu(self.menuBar)
        self.menuStop_Motion_Studio.setObjectName("menuStop_Motion_Studio")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuStop_Motion_Studio.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.captureButton.setText(_translate("MainWindow", "Capture"))
        self.playButton.setText(_translate("MainWindow", "Play"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.exportButton.setText(_translate("MainWindow", "Export"))
        self.currentFrameLabel.setText(_translate("MainWindow", "Current Frame"))
        self.label_3.setText(_translate("MainWindow", "/"))
        self.speedGroup.setTitle(_translate("MainWindow", "Speed"))
        self.slowRadio.setText(_translate("MainWindow", "slow"))
        self.mediumRadio.setText(_translate("MainWindow", "medium"))
        self.fullRadio.setText(_translate("MainWindow", "full"))
        self.cameraSettings.setTitle(_translate("MainWindow", "Camera Settings"))
        self.label.setText(_translate("MainWindow", "Brightness"))
        self.label_2.setText(_translate("MainWindow", "Contrast"))
        self.label_4.setText(_translate("MainWindow", "drc_strength"))
        self.drcComboBox.setCurrentText(_translate("MainWindow", "off"))
        self.drcComboBox.setItemText(0, _translate("MainWindow", "off"))
        self.drcComboBox.setItemText(1, _translate("MainWindow", "low"))
        self.drcComboBox.setItemText(2, _translate("MainWindow", "medium"))
        self.drcComboBox.setItemText(3, _translate("MainWindow", "high"))
        self.label_5.setText(_translate("MainWindow", "exposure mode"))
        self.exposureComboBox.setCurrentText(_translate("MainWindow", "off"))
        self.exposureComboBox.setItemText(0, _translate("MainWindow", "off"))
        self.exposureComboBox.setItemText(1, _translate("MainWindow", "night"))
        self.exposureComboBox.setItemText(2, _translate("MainWindow", "nightpreview"))
        self.exposureComboBox.setItemText(3, _translate("MainWindow", "backlight"))
        self.exposureComboBox.setItemText(4, _translate("MainWindow", "spotlight"))
        self.exposureComboBox.setItemText(5, _translate("MainWindow", "sports"))
        self.exposureComboBox.setItemText(6, _translate("MainWindow", "snow"))
        self.exposureComboBox.setItemText(7, _translate("MainWindow", "beach"))
        self.exposureComboBox.setItemText(8, _translate("MainWindow", "verylong"))
        self.exposureComboBox.setItemText(9, _translate("MainWindow", "fixedfps"))
        self.exposureComboBox.setItemText(10, _translate("MainWindow", "antishake"))
        self.exposureComboBox.setItemText(11, _translate("MainWindow", "fireworks"))
        self.exposureComboBox.setItemText(12, _translate("MainWindow", "auto"))
        self.label_6.setText(_translate("MainWindow", "exposure compensation"))
        self.flipCheckBox.setText(_translate("MainWindow", "flip"))
        self.denoiseCheckBox.setText(_translate("MainWindow", "denoise"))
        self.label_7.setText(_translate("MainWindow", "effect"))
        self.effectComboBox.setCurrentText(_translate("MainWindow", "none"))
        self.effectComboBox.setItemText(0, _translate("MainWindow", "none"))
        self.effectComboBox.setItemText(1, _translate("MainWindow", "negative"))
        self.effectComboBox.setItemText(2, _translate("MainWindow", "solarize"))
        self.effectComboBox.setItemText(3, _translate("MainWindow", "sketch"))
        self.effectComboBox.setItemText(4, _translate("MainWindow", "denoise"))
        self.effectComboBox.setItemText(5, _translate("MainWindow", "emboss"))
        self.effectComboBox.setItemText(6, _translate("MainWindow", "oilpaint"))
        self.effectComboBox.setItemText(7, _translate("MainWindow", "hatch"))
        self.effectComboBox.setItemText(8, _translate("MainWindow", "gpen"))
        self.effectComboBox.setItemText(9, _translate("MainWindow", "pastel"))
        self.effectComboBox.setItemText(10, _translate("MainWindow", "watercolor"))
        self.effectComboBox.setItemText(11, _translate("MainWindow", "film"))
        self.effectComboBox.setItemText(12, _translate("MainWindow", "blur"))
        self.effectComboBox.setItemText(13, _translate("MainWindow", "saturation"))
        self.effectComboBox.setItemText(14, _translate("MainWindow", "colorswap"))
        self.effectComboBox.setItemText(15, _translate("MainWindow", "washedout"))
        self.effectComboBox.setItemText(16, _translate("MainWindow", "posterize"))
        self.effectComboBox.setItemText(17, _translate("MainWindow", "colorpoint"))
        self.effectComboBox.setItemText(18, _translate("MainWindow", "colorbalance"))
        self.effectComboBox.setItemText(19, _translate("MainWindow", "cartoon"))
        self.effectComboBox.setItemText(20, _translate("MainWindow", "deinterlace1"))
        self.effectComboBox.setItemText(21, _translate("MainWindow", "deinterlace2"))
        self.label_8.setText(_translate("MainWindow", "iso"))
        self.applyButton.setText(_translate("MainWindow", "apply"))
        self.resetButton.setText(_translate("MainWindow", "reset"))
        self.menuStop_Motion_Studio.setTitle(_translate("MainWindow", "Stop Motion Studio"))

