# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.dial = QtWidgets.QDial(self.centralWidget)
        self.dial.setGeometry(QtCore.QRect(330, 350, 50, 64))
        self.dial.setMinimum(1)
        self.dial.setMaximum(10)
        self.dial.setPageStep(10)
        self.dial.setProperty("value", 1)
        self.dial.setTracking(True)
        self.dial.setWrapping(True)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName("dial")
        self.captureButton = QtWidgets.QPushButton(self.centralWidget)
        self.captureButton.setGeometry(QtCore.QRect(30, 360, 93, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.captureButton.sizePolicy().hasHeightForWidth())
        self.captureButton.setSizePolicy(sizePolicy)
        self.captureButton.setObjectName("captureButton")
        self.frameRateSpinBox = QtWidgets.QSpinBox(self.centralWidget)
        self.frameRateSpinBox.setGeometry(QtCore.QRect(180, 410, 42, 22))
        self.frameRateSpinBox.setMinimum(1)
        self.frameRateSpinBox.setMaximum(30)
        self.frameRateSpinBox.setObjectName("frameRateSpinBox")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(150, 390, 81, 16))
        self.label.setObjectName("label")
        self.numFramesSpinBox = QtWidgets.QSpinBox(self.centralWidget)
        self.numFramesSpinBox.setGeometry(QtCore.QRect(250, 410, 42, 22))
        self.numFramesSpinBox.setObjectName("numFramesSpinBox")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(240, 390, 71, 20))
        self.label_2.setObjectName("label_2")
        self.playButton = QtWidgets.QPushButton(self.centralWidget)
        self.playButton.setGeometry(QtCore.QRect(30, 400, 93, 28))
        self.playButton.setObjectName("playButton")
        self.deleteButton = QtWidgets.QPushButton(self.centralWidget)
        self.deleteButton.setGeometry(QtCore.QRect(390, 360, 93, 28))
        self.deleteButton.setObjectName("deleteButton")
        self.exportButton = QtWidgets.QPushButton(self.centralWidget)
        self.exportButton.setGeometry(QtCore.QRect(390, 400, 93, 28))
        self.exportButton.setObjectName("exportButton")
        self.imageView = QtWidgets.QLabel(self.centralWidget)
        self.imageView.setGeometry(QtCore.QRect(30, 20, 441, 301))
        self.imageView.setText("")
        self.imageView.setScaledContents(True)
        self.imageView.setObjectName("imageView")
        self.currentFrameLabel = QtWidgets.QLabel(self.centralWidget)
        self.currentFrameLabel.setGeometry(QtCore.QRect(220, 350, 91, 16))
        self.currentFrameLabel.setObjectName("currentFrameLabel")
        self.currentFrame = QtWidgets.QLineEdit(self.centralWidget)
        self.currentFrame.setGeometry(QtCore.QRect(220, 370, 31, 22))
        self.currentFrame.setObjectName("currentFrame")
        self.numFrames = QtWidgets.QLineEdit(self.centralWidget)
        self.numFrames.setGeometry(QtCore.QRect(280, 370, 31, 22))
        self.numFrames.setObjectName("numFrames")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(260, 370, 55, 16))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuStop_Motion_Studio = QtWidgets.QMenu(self.menuBar)
        self.menuStop_Motion_Studio.setObjectName("menuStop_Motion_Studio")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuStop_Motion_Studio.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.captureButton.setText(_translate("MainWindow", "Capture"))
        self.label.setText(_translate("MainWindow", "Frame Rate"))
        self.label_2.setText(_translate("MainWindow", "# Frames"))
        self.playButton.setText(_translate("MainWindow", "Play"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.exportButton.setText(_translate("MainWindow", "Export"))
        self.currentFrameLabel.setText(_translate("MainWindow", "Current Frame"))
        self.label_3.setText(_translate("MainWindow", "/"))
        self.menuStop_Motion_Studio.setTitle(_translate("MainWindow", "Stop Motion Studio"))

